### ISSUE TITLE
feat: Add favicon

### ISSUE THREAD

**Issue by imarchit19** [imarchit19/Drum-Kit#3]
Add favicon to page.

**Comment by sumitsawant** [comment]
I can work on this @imarchit19 ,will you assign me this ?

**Comment by mohammadanang** [comment]
@imarchit19 what's icon do you want?

**Comment by RuanAragao** [comment]
![android-chrome-512x512](https://user-images.githubusercontent.com/1015013/95020019-0b773480-063f-11eb-9616-1edb1f245b07.png)

**Comment by Eshwar5799** [comment]
I can work on this @imarchit19 , will you assign this to me
